module.exports = [
	{
		title: 'Welcome +10',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '5',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#620887',
		verses:[
            `2**Isaiah 42:1**Behold, my servant, whom I uphold, my chosen, in whom my soul delights: I have put my Spirit on him. He will bring justice to the nations.`,
            `2**2 Corinthians 8:9**For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sakes he became poor, that you through his poverty might become rich.`,
            `2**Isaiah 14:12**How you have fallen from heaven, shining one, son of the dawn! How you are cut down to the ground, who laid the nations low!`,
            `2**Ecclesiastes 2:22**For what does a man have of all his labor and of the striving of his heart, in which he labors under the sun?`,
            `2**Daniel 9:19**Lord, hear. Lord, forgive. Lord, listen and do. Don’t defer, for your own sake, my God, because your city and your people are called by your name.`
            ]
    },
	{
		title: 'Dedicated +50',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '10',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#f4ce57',
		verses:[
            `2**Proverbs 22:6**Train up a child in the way he should go, and when he is old he will not depart from it.`,
            `2**Luke 12:26**If then you aren’t able to do even the least things, why are you anxious about the rest?`,
            `2**2 Peter 1:6**And in knowledge, self-control; and in self-control perseverance; and in perseverance godliness`,
            `2**2 Timothy 4:2**Preach the word; be urgent in season and out of season; reprove, rebuke, and exhort with all patience and teaching.`,
            `2**Revelation 2:3**You have perseverance and have endured for my name’s sake, and have not grown weary.`,
            `2**John 14:16**I will pray to the Father, and he will give you another Counselor, that he may be with you forever`,
            `2**Isaiah 41:10**Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness`,
            `2**Mark 9:24**Immediately the father of the child cried out with tears, “I believe. Help my unbelief!”`,
            `2**Proverbs 4:23**Keep your heart with all diligence, for out of it is the wellspring of life.`,
            `2**Matthew 6:28**Why are you anxious about clothing? Consider the lilies of the field, how they grow. They don’t toil, neither do they spin`
            ]
    },
	{
		title: 'Talented +100',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '10',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#f2404c',
		verses:[
            `2**Acts 4:12**There is salvation in no one else, for there is no other name under heaven that is given among men, by which we must be saved!`,
            `2**Matthew 5:7**Blessed are the merciful, for they shall obtain mercy.`,
            `2**Exodus 34:6**The Lord passed by before him, and proclaimed, “the Lord! the Lord, a merciful and gracious God, slow to anger, and abundant in loving kindness and truth`,
            `2**Ephesians 1:3**Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ`,
            `2**Matthew 5:16**Even so, let your light shine before men; that they may see your good works, and glorify your Father who is in heaven.`,
            `2**2 Timothy 3:16**Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness`,
            `2**2 Corinthians 11:17**That which I speak, I don’t speak according to the Lord, but as in foolishness, in this confidence of boasting.`,
            `2**Galatians 2:20**I have been crucified with Christ, and it is no longer I that live, but Christ lives in me.`,
            `2**Ephesians 4:1**I therefore, the prisoner in the Lord, beg you to walk worthily of the calling with which you were called`,
            `2**Ephesians 2:10**For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them.`
            ]
    },
	{
		title: 'Skilled +250',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '10',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#0817a2',
		verses:[
            `2**1 Thessalonians 3:7**For this cause, brothers, we were comforted over you in all our distress and affliction through your faith.`,
            `2**Matthew 10:34**Don’t think that I came to send peace on the earth. I didn’t come to send peace, but a sword.`,
            `2**Acts 11:18**When they heard these things, they held their peace, and glorified God, saying, “Then God has also granted to the Gentiles repentance to life!”`,
            `2**Titus 2:11**For the grace of God has appeared, bringing salvation to all men`,
            `2**1 Corinthians 15:50**Now I say this, brothers, that flesh and blood can’t inherit God’s Kingdom; neither does the perishable inherit imperishable.`,
            `2**Matthew 5:9**Blessed are the peacemakers, for they shall be called children of God.`,
            `2**Mark 10:17**As he was going out into the way, one ran to him, knelt before him, and asked him, “Good Teacher, what shall I do that I may inherit eternal life?”`,
            `2**Psalms 1:1**Blessed is the man who doesn’t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers`,
            `2**Lamentations 3:22**It is because of the Lord’s loving kindnesses that we are not consumed, because his compassion doesn’t fail.`,
            `2**Luke 1:30**The angel said to her, “Don’t be afraid, Mary, for you have found favor with God.`
            ]
    },
	{
		title: 'Seasoned +500',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '20',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#6e097d',
		verses:[
            `2**John 5:39**You search the Scriptures, because you think that in them you have eternal life; and these are they which testify about me.`,
            `2**Matthew 1:21**She shall give birth to a son. You shall call his name Jesus, for it is he who shall save his people from their sins.”`,
            `2**Colossians 4:2**Continue steadfastly in prayer, watching in it with thanksgiving`,
            `2**Job 6:10**Let still be my consolation, yes, let me exult in pain that doesn’t spare, that I have not denied the words of the Holy One.`,
            `2**Luke 2:14**Glory to God in the highest, on earth peace, good will toward men.”`,
            `2**Philippians 4:7**And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.`,
            `2**Acts 16:17**Following Paul and us, she cried out, “These men are servants of the Most High God, who proclaim to us a way of salvation!”`,
            `2**Matthew 5:6**Blessed are those who hunger and thirst after righteousness, for they shall be filled.`,
            `2**Genesis 2:3**God blessed the seventh day, and made it holy, because he rested in it from all his work of creation which he had done.`,
            `2**Psalms 138:2**I will bow down toward your holy temple, and give thanks to your Name for your loving kindness and for your truth; for you have exalted your Name and your Word above all.`,
            `2**James 5:13**Is any among you suffering? Let him pray. Is any cheerful? Let him sing praises.`,
            `2**Colossians 3:17**Whatever you do, in word or in deed, do all in the name of the Lord Jesus, giving thanks to God the Father, through him.`,
            `2**1 Samuel 10:10**When they came there to the hill, behold, a band of prophets met him; and the Spirit of God came mightily on him, and he prophesied among them.`,
            `2**John 6:51**I am the living bread which came down out of heaven. If anyone eats of this bread, he will live forever. Yes, the bread which I will give for the life of the world is my flesh.”`,
            `2**Job 21:34**So how can you comfort me with nonsense, because in your answers there remains only falsehood?”`,
            `2**Hebrews 13:6**So that with good courage we say, “The Lord is my helper. I will not fear. What can man do to me?”`,
            `2**Ephesians 4:3**Being eager to keep the unity of the Spirit in the bond of peace.`,
            `2**Matthew 25:34**Then the King will tell those on his right hand, ‘Come, blessed of my Father, inherit the Kingdom prepared for you from the foundation of the world`,
            `2**Joel 2:13**Tear your heart, and not your garments, and turn to the Lord, your God; for he is gracious and merciful, slow to anger, and abundant in loving kindness, and relents from sending calamity.`,
            `2**1 Peter 3:11**Let him turn away from evil and do good. Let him seek peace and pursue it.`
            ]
    },
	{
		title: 'Expert +1000',
		index: '',
		type: 'mypack',
		show: 'true',
		num_verses: '25',
		num_solved: '0',
		solved: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        product_id: 'bonus.0.collection.0',
		bg_color: '#f5eaf6',
		verses:[
            `2**James 1:5**But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.`,
            `2**Acts 2:4**They were all filled with the Holy Spirit, and began to speak with other languages, as the Spirit gave them the ability to speak.`,
            `2**Hebrews 11:6**Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him.`,
            `2**Revelation 21:1**I saw a new heaven and a new earth: for the first heaven and the first earth have passed away, and the sea is no more.`,
            `2**Matthew 5:3**Blessed are the poor in spirit, for theirs is the Kingdom of Heaven.`,
            `2**Hebrews 4:14**Having then a great high priest who has passed through the heavens, Jesus, the Son of God, let’s hold tightly to our confession.`,
            `2**Daniel 7:13**I saw in the night visions, and behold, there came with the clouds of the sky one like a son of man`,
            `2**Genesis 1:8**God called the expanse “sky”. There was evening and there was morning, a second day.`,
            `2**John 3:13**No one has ascended into heaven but he who descended out of heaven, the Son of Man, who is in heaven.`,
            `2**Isaiah 66:13**As one whom his mother comforts, so I will comfort you. You will be comforted in Jerusalem.”`,
            `2**Romans 10:15**And how will they preach unless they are sent? As it is written: “How beautiful are the feet of those who preach the Good News of peace, who bring glad tidings of good things!”`,
            `2**1 Peter 1:9**Receiving the result of your faith: the salvation of your souls.`,
            `2**Psalms 34:8**Oh taste and see that the Lord is good. Blessed is the man who takes refuge in him.`,
            `2**2 Samuel 16:17**Absalom said to Hushai, “Is this your kindness to your friend? Why didn’t you go with your friend?”`,
            `2**Isaiah 30:18**Therefore the Lord will wait, that he may be gracious to you; and therefore he will be exalted, that he may have mercy on you, for the Lord is a God of justice.`,
            `2**Psalms 107:1**Give thanks to the Lord, for he is good, for his loving kindness endures forever.`,
            `2**2 Corinthians 1:3**Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort`,
            `2**Hebrews 13:15**Through him, then, let’s offer up a sacrifice of praise to God continually, that is, the fruit of lips which proclaim allegiance to his name.`,
            `2**Acts 16:25**But about midnight Paul and Silas were praying and singing hymns to God, and the prisoners were listening to them.`,
            `2**Job 32:8**But there is a spirit in man, and the Spirit of the Almighty gives them understanding.`,
            `2**Romans 8:11**But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.`,
            `2**John 6:47**Most certainly, I tell you, he who believes in me has eternal life.`,
            `2**Exodus 20:12**Honor your father and your mother, that your days may be long in the land which the Lord your God gives you.`,
            `2**James 2:14**What good is it, my brothers, if a man says he has faith, but has no works? Can faith save him?`,
            `2**Galatians 3:26**For you are all children of God, through faith in Christ Jesus.`
            ]
    }
];